baseURL = 'https://donvink.github.io/stock-review/'
title = 'AI 股市洞察 | AI Stock Insight'
theme = "PaperMod"
googleAnalytics = "G-DBWSC03BX5"

# 默认语言设置
defaultContentLanguage = 'en'
enableRobotsTXT = true

[params]
    author = "Leo Zhong"
    defaultTheme = "auto"
    showFullContents = false 
    displayFullLangName = true
    showLanguagePicker = true # 开启语言切换按钮
    mainSections = ["posts"]

    [params.assets]
        disableHLJS = false 

# ----------------- 中文配置 -----------------
[languages.zh]
    languageName = "中文"
    contentDir = "content/zh"
    weight = 1
    [languages.zh.params.homeInfoParams]
        Title = "📈 每日股市 AI 分析"
        Content = "💡 **Smart Market Insight, Powered by AI.**\n\n自动化驱动，AI 深度复盘。利用技术力量，捕捉每一份全球市场机遇。"
    
    [[languages.zh.menu.main]]
        identifier = "posts"
        name = "资讯档案"
        url = "posts/"
        weight = 10

# ----------------- 英文配置 -----------------
[languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2
    [languages.en.params.homeInfoParams]
        Title = "📈 Daily AI Stock Analysis"
        Content = "💡 **Smart Market Insight, Powered by AI.**\n\nAutomated workflows for deep AI-driven market review. Capturing every global opportunity with technology."

    [[languages.en.menu.main]]
        identifier = "posts"
        name = "Archive"
        url = "posts/"
        weight = 10

[markup.goldmark.renderer]
    unsafe = true